defaults: &defaults
  working_directory: ~/api-docs
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      # Restore bundle cache
      - restore_cache:
          keys:
            - api-docs-bundle-{{ checksum "Gemfile.lock" }}
            - api-docs-bundle-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # Store bundle cache
      - save_cache:
          key: api-docs-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/api-docs
      - run: bundle exec middleman build --clean
  build_and_deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/api-docs
      - add_ssh_keys:
          fingerprints:
            - "f0:83:af:ff:f2:05:87:f5:da:71:46:6a:8c:0c:24:5c"
      - run:
          name: Deploy docs
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config user.email "devops@coinweb.io"
            git config user.name "coinweb-devops"
            ./deploy.sh
workflows:
  version: 2
  build_and_release:
    jobs:
      - install
      - build:
          requires:
            - install
          filters:
            branches:
              ignore: master
      - build_and_deploy:
          requires:
            - install
          filters:
            branches:
              only: master
